apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aegis-service.name" . }}
    app.kubernetes.io/part-of: aegis-rag
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aegis-service.name" . }}

