"""Generate Helm values files from the AegisRAG service catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SERVICE_CATALOG_PATH = ROOT / "infra" / "service-catalog" / "aegis-services.json"
VALUES_DIR = ROOT / "infra" / "helm" / "values"

SERVICE_URL_ENV = {
    "entitlement-service": "AEGIS_ENTITLEMENT_URL",
    "policy-service": "AEGIS_POLICY_URL",
    "context-service": "AEGIS_CONTEXT_URL",
    "retrieval-service": "AEGIS_RETRIEVAL_URL",
    "llm-gateway": "AEGIS_LLM_GATEWAY_URL",
    "verification-service": "AEGIS_VERIFICATION_URL",
    "observability-service": "AEGIS_OBSERVABILITY_URL",
}


def main() -> int:
    catalog = json.loads(SERVICE_CATALOG_PATH.read_text(encoding="utf-8"))
    services = catalog["services"]
    VALUES_DIR.mkdir(parents=True, exist_ok=True)
    for service_name in sorted(services):
        path = VALUES_DIR / f"{service_name}-dev.yaml"
        path.write_text(render_values(service_name, services[service_name]), encoding="utf-8")
    print(f"Generated {len(services)} Helm values files in {VALUES_DIR}")
    return 0


def render_values(service_name: str, service: dict[str, Any]) -> str:
    env = {
        "PORT": "8000",
        "AEGIS_SERVICE_APP": service["app"],
        **service.get("env", {}),
    }
    if service_name == "assistant-api":
        for dependency in service["dependencies"]:
            env_name = SERVICE_URL_ENV.get(dependency)
            if env_name:
                env[env_name] = f"http://{dependency}:8000"

    lines = [
        "# Generated by scripts/infra/generate_helm_values.py. Do not edit by hand.",
        f"nameOverride: {service_name}",
        "",
        "image:",
        f"  repository: example/{service_name}",
        '  tag: "0.1.0"',
        "",
        "service:",
        "  type: ClusterIP",
        "  port: 8000",
        "  targetPort: 8000",
        "",
        "env:",
    ]
    for name, value in sorted(env.items()):
        lines.extend(
            [
                f"  - name: {name}",
                f"    value: {json.dumps(str(value))}",
            ]
        )
    lines.extend(
        [
            "",
            "readinessProbe:",
            f"  path: {service['healthReadyPath']}",
            "",
            "livenessProbe:",
            f"  path: {service['healthLivePath']}",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
