"""Generate Kubernetes NetworkPolicies from the AegisRAG service catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SERVICE_CATALOG_PATH = ROOT / "infra" / "service-catalog" / "aegis-services.json"
OUTPUT_PATH = ROOT / "infra" / "kubernetes" / "network-policies" / "catalog-service-traffic.yaml"
NAMESPACE = "aegis-apps"


def main() -> int:
    catalog = json.loads(SERVICE_CATALOG_PATH.read_text(encoding="utf-8"))
    rendered = render_network_policies(catalog["services"])
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Generated Kubernetes network policies at {OUTPUT_PATH}")
    return 0


def render_network_policies(services: dict[str, dict[str, Any]]) -> str:
    assistant_dependencies = sorted(services["assistant-api"]["dependencies"])
    documents = [render_assistant_egress_policy(assistant_dependencies)]
    documents.extend(
        render_dependency_ingress_policy(dependency) for dependency in assistant_dependencies
    )
    return "---\n".join(documents)


def render_assistant_egress_policy(dependencies: list[str]) -> str:
    lines = [
        "# Generated by scripts/infra/generate_kubernetes_network_policies.py.",
        "# Do not edit by hand.",
        "apiVersion: networking.k8s.io/v1",
        "kind: NetworkPolicy",
        "metadata:",
        "  name: allow-assistant-egress-to-dependencies",
        f"  namespace: {NAMESPACE}",
        "spec:",
        "  podSelector:",
        "    matchLabels:",
        "      app.kubernetes.io/name: assistant-api",
        "  policyTypes:",
        "    - Egress",
        "  egress:",
    ]
    for dependency in dependencies:
        lines.extend(
            [
                "    - to:",
                "        - podSelector:",
                "            matchLabels:",
                f"              app.kubernetes.io/name: {dependency}",
                "      ports:",
                "        - protocol: TCP",
                "          port: 8000",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def render_dependency_ingress_policy(dependency: str) -> str:
    return "\n".join(
        [
            "apiVersion: networking.k8s.io/v1",
            "kind: NetworkPolicy",
            "metadata:",
            f"  name: allow-{dependency}-ingress-from-assistant",
            f"  namespace: {NAMESPACE}",
            "spec:",
            "  podSelector:",
            "    matchLabels:",
            f"      app.kubernetes.io/name: {dependency}",
            "  policyTypes:",
            "    - Ingress",
            "  ingress:",
            "    - from:",
            "        - podSelector:",
            "            matchLabels:",
            "              app.kubernetes.io/name: assistant-api",
            "      ports:",
            "        - protocol: TCP",
            "          port: 8000",
            "",
        ]
    )


if __name__ == "__main__":
    sys.exit(main())
